### ISSUE TITLE
Doesn't work with current patch 7.11

### ISSUE THREAD

**Issue by KisaEternity** [anomek/AutoTravel#1]
Any plans to fix? Cheers 👀

**Comment by anomek** [comment]
Hi,
I'm unfortunately away from home, and can't realistically fix that without my tools.
I will fix it when i'm back ~~ first week of January 2025, sorry

**Comment by KisaEternity** [comment]
All good dw, tyt. Was just checking😊

**Comment by anomek** [comment]
Fixed in 0.0.4.0
